name: "Release gateway"

on:
  pull_request:
  
jobs: 
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps: 
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --legacy-peer-deps
      - name: Prepare build
        run: yarn run build 